### ISSUE TITLE
GPL v3 and Android Play Store

### ISSUE THREAD

**Issue by leaf-node** [AhsanSarwar45/flutter_boot_receiver#1]
Thanks for your project. : )

I'm wondering if you would be willing to change the license on this project to MIT? I'm writing a free software Flutter app with the MIT license, and I'm not sure that it's legal for me to upload third party GPL code to the play store. (I also plan on uploading to F-Droid). That's because I am not the copyright holder of your code, and it's not clear to me that Google is accepting the responsibility to distribute code if I provide a binary and source code to them, so the version I give them might have to be technically proprietary, even if I do provide others freely licensed source code elsewhere.

Of course, I'm not a lawyer, but I haven't found any clear search results that say this is permissible for me to do. Would you be willing to change the license of this project to make it easier to use on Android?

**Comment by AhsanSarwar45** [comment]
Sorry for late reply. This seems like a good idea and I have changed the license to MIT.

**Comment by leaf-node** [comment]
Thanks so much! 😀

Would you mind updating the version on pub.dev, or update the license metadata? It still says GPLv3.
