### ISSUE TITLE
License on pub.dev

### ISSUE THREAD

**Issue by leaf-node** [AhsanSarwar45/flutter_boot_receiver#3]
Thanks so much for your resolution to issue #1! 😀

I commented on that issue after it was closed, but decided to make a new issue here so you can see it .

Would you mind updating the license version on pub.dev, or update the license metadata? It still says GPL-3.0 instead of MIT.

Thanks!

**Comment by AhsanSarwar45** [comment]
Hi, yeah sorry, will update it shortly, thanks for reminding.

Off topic, but is this library working well on the devices you have tested? If not, would love to hear about it. I am using this for my clock app (https://github.com/vicolo-dev/chrono), but have tested it on only a limited amount of devices.

**Comment by leaf-node** [comment]
I'll try integrating it into my app and test it on my Pixel 8 and the Android emulator.

I think HTC phones (or another phone brand) may need an extra line in `AndroidManifest.xml`. Not sure where I found it, but could try searching the web for "HTC start on boot", etc

**Comment by AhsanSarwar45** [comment]
I've updated the license in 1.2.0 on pub.dev.
